version: '3.8'

services:
  # FastAPI Trading Server (Production Ready)
  kite-trading:
    command: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kite-trading-server
    ports:
      - "8080:8000"
    environment:
      - PYTHONPATH=/app
      - KITE_API_KEY=${KITE_API_KEY}
      - KITE_API_SECRET=${KITE_API_SECRET}
      - KITE_REDIRECT_URI=${KITE_REDIRECT_URI}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LOG_FILE=/app/logs/order.log
      - DOCKER_MODE=true
      - BROWSER_REAUTH=true
    volumes:
      - kite_data:/app/data
      - kite_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "description=Kite Trading API Server for ChatGPT Integration"
      - "version=1.0.0"

volumes:
  kite_data:
    driver: local
  kite_logs:
    driver: local

networks:
  default:
    name: kite-trading-network
