version: '3.8'

services:
  # Kite Trading Server
  kite-trading:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kite-trading-server
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - KITE_API_KEY=${KITE_API_KEY}
      - KITE_API_SECRET=${KITE_API_SECRET}
      - KITE_REDIRECT_URI=${KITE_REDIRECT_URI}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LOG_FILE=order.log
    volumes:
      # Mount data directory for persistent sessions and logs
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: kite-trading-network
