version: '3.8'

services:
  # Production Kite Trading Server
  kite-trading:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kite-trading-prod
    ports:
      - "80:8000"
      - "443:8000"
    environment:
      - PYTHONPATH=/app
      - KITE_API_KEY=${KITE_API_KEY}
      - KITE_API_SECRET=${KITE_API_SECRET}
      - KITE_REDIRECT_URI=${KITE_REDIRECT_URI}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LOG_FILE=/app/logs/order.log
      - DOCKER_MODE=true
      - BROWSER_REAUTH=true
      - ENVIRONMENT=production
    volumes:
      - kite_data:/app/data
      - kite_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "description=Kite Trading API Server - Production"
      - "version=1.0.0"
      - "environment=production"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: kite-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kite-trading
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  kite_data:
    driver: local
  kite_logs:
    driver: local

networks:
  default:
    name: kite-trading-network
